#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Migration::Utils qw/ensure_socialtext_schema/;

ensure_socialtext_schema(64); # Current version when this migration written

exit 0;
