#!/usr/bin/perl
use strict;
use warnings;
use Socialtext::AppConfig;
use Socialtext::JobCreator;
use Socialtext::Workspace;

my $ceq_dir = Socialtext::AppConfig->change_event_queue_dir;
my $data_dir = Socialtext::AppConfig->data_root_dir;

my @links = glob("$ceq_dir/*");
for my $link (@links) {
    next unless -l $link;
    my $dest = readlink $link;

    (my $shortdest = $dest) =~ s#^\Q$data_dir\E/##;
    if (-f $link) {
        queue_attachment_index($link, $shortdest);
    }
    else {
        queue_page_index($link, $shortdest);
    }
}

exit 0;


sub queue_attachment_index {
    my $symlink = shift;
    my $path = shift;
    # eg: plugin/admin/attachments/admin/20090304185150-25-21807/myconversations128.gif
    if ($path =~ m#^plugin/([^/]+)/attachments/([^/]+)/([^/]+)/(.+)$#) {
        my ($ws_name, $page_id, $attach_id, $attach_name) = ($1, $2, $3, $4);
        print "  Found attachment index job: $ws:$page_id - $attach_name\n";
        my $ws = Socialtext::Workspace->new( name => $ws_name );
        next unless $ws;

        Socialtext::JobCreator->index_attachment(
            workspace_id => $ws->workspace_id,
            page_id => $page_id,
            attach_id => $attach_id,
        );

        unlink $symlink or warn "Could not unlink $symlink: $!";
    }
    else {
        warn "Unknown attachment symlink: $path";
    }
}

sub queue_page_index {
    my $symlink = shift;
    my $path = shift;

    # data/admin/people/
    if ($path =~ m#^data/([^/]+)/(.+)$#) {
        my ($ws_name, $page_id) = ($1, $2);
        print "  Found page index job: $ws:$page_id\n";

        my $ws = Socialtext::Workspace->new( name => $ws_name );
        next unless $ws;

        Socialtext::JobCreator->index_page(
            workspace_id => $ws->workspace_id,
            page_id => $page_id,
        );

        unlink $symlink or warn "Could not unlink $symlink: $!";
    }
    else {
        warn "Unknown page symlink: $path";
    }
}
