#!/bin/bash

NLW_BIN="$ST_CURRENT/nlw/bin"
NLW_DEVBIN="$ST_CURRENT/nlw/dev-bin"
USERNAME="wikitester@ken.socialtext.net"

echo Set up  test-data workspace
$NLW_DEVBIN/create-test-data-workspace
$NLW_BIN/st-admin create-user --e $USERNAME >/dev/null 2>/dev/null || true
$NLW_BIN/st-admin add-workspace-admin --w test-data --e $USERNAME >/dev/null 2>/dev/null || true
$NLW_BIN/st-admin give-accounts-admin  --e $USERNAME  >/dev/null 2>/dev/null || true
$NLW_BIN/st-admin give-system-admin  --e $USERNAME  >/dev/null 2>/dev/null || true

echo "Set up wikitests"
    $NLW_DEVBIN/wikitests-to-wiki

echo ENABLING Socialcalc for all workspaces
$NLW_DEVBIN/st-socialcalc enable

echo "CTRL-C to halt reports DB setup"

echo ""
echo Populating reports DB
$NLW_DEVBIN/st-populate-reports-db
# run report populater again because that seems to be necessary for the
# report tests to pass
export PGUSER=`st-config echo db_user`
$NLW_DEVBIN/st-populate-reports-db

echo Done setting up wikitests
